image: androidsdk/android-30

stages:
  - check
  - build

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

check:
  stage: check
  script:
    - ./gradlew detekt

build:
  stage: build
  script:
    - ./gradlew assembleDebug